Repository DeepLabCut/DeepLabCut, pull requests merged in 2020-09, with the labels that each got.

#879 pin matplotlib and numba for stability
  setup.py
Labels: Feature-request

#870 Added delete button in labelling_toolbox screen
  deeplabcut/generate_training_dataset/labeling_toolbox.py
  deeplabcut/generate_training_dataset/multiple_individuals_labeling_toolbox.py
Labels: GUI, enhancement

#831 a dedicated maDLC page
  docs/installation.md
  docs/maDLC_AdvUserGuide.md
Labels: documentation

#923 Update maDLC_AdvUserGuide.md
  docs/maDLC_AdvUserGuide.md
Labels: documentation
