Repository DeepLabCut/DeepLabCut, pull requests merged in 2020-07, with the labels that each got.

#777 Deleted markers are no longer considered annotated
  deeplabcut/generate_training_dataset/labeling_toolbox.py
Labels: bug fix!

#795 Create python-package.yml
  .github/workflows/python-package.yml
  README.md
  requirements.txt
Labels: enhancement

#765 Improved TrackletManager
  deeplabcut/gui/refine_tracklets.py
  deeplabcut/post_processing/filtering.py
  deeplabcut/refine_training_dataset/tracklets.py
  docs/UseOverviewGuide.md
  docs/functionDetails.md
Labels: WORK IN PROGRESS!, enhancement
