Repository DeepLabCut/DeepLabCut, pull requests merged in 2020-05, with the labels that each got.

#671 Fix for bug #670, #581 ...
  deeplabcut/generate_training_dataset/auxfun_drag_label.py
  deeplabcut/generate_training_dataset/labeling_toolbox.py
  deeplabcut/refine_training_dataset/auxfun_drag.py
  deeplabcut/refine_training_dataset/refinement.py
Labels: bug fix!

#680 Update Auxiliary Function read_config()
  deeplabcut/utils/auxiliaryfunctions.py
Labels: enhancement

#708 Labeling GUI now correctly handles addition of bodyparts to a maDLC project
  deeplabcut/generate_training_dataset/multiple_individuals_labeling_toolbox.py
Labels: GUI

#717 Better SkeletonBuilder
  deeplabcut/utils/auxfun_multianimal.py
  deeplabcut/utils/skeleton.py
Labels: enhancement
