Repository DeepLabCut/DeepLabCut, pull requests merged in 2020-06, with the labels that each got.

#718 also convert to uniquebpt
  deeplabcut/utils/auxfun_multianimal.py
  docs/convert_maDLC.md
Labels: enhancement

#750 Skeleton analysis now supports 2.2
  deeplabcut/post_processing/analyze_skeleton.py
  deeplabcut/utils/auxiliaryfunctions.py
Labels: backwards compatibility, enhancement

#746 Update CONTRIBUTING.md
  AUTHORS
  CONTRIBUTING.md
Labels: Community feedback requested

#748 Parallelizes creation of labeled videos
  deeplabcut/utils/make_labeled_video.py
Labels: enhancement

#755 Fix padding when checking labels
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/utils/visualization.py
Labels: bug fix!

#764 Reindex labeled data to match config individual and bodypart order
  deeplabcut/generate_training_dataset/multiple_individuals_labeling_toolbox.py
Labels: bug fix!

#763 Fix SkeletonBuilder
  deeplabcut/utils/skeleton.py
Labels: bug fix!

#773 Only rely on ffprobe when robust metadata are desired
  deeplabcut/gui/analyze_videos.py
  deeplabcut/pose_estimation_tensorflow/predict_multianimal.py
Labels: bug fix!
