Repository DeepLabCut/DeepLabCut, pull requests merged in 2021-12, with the labels that each got.

#1596 Minor fixes for single point tracking
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/utils/make_labeled_video.py
  deeplabcut/utils/video_processor.py
Labels: bug fix!

#1584 Better format for cross-platform labelling and training (storing triples)
  deeplabcut/__init__.py
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/gui/labeling_toolbox.py
  deeplabcut/gui/multiple_individuals_labeling_toolbox.py
  deeplabcut/gui/multiple_individuals_refinement_toolbox.py
  deeplabcut/gui/outlier_frame_extraction_toolbox.py
  deeplabcut/gui/refinement.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/utils/auxfun_multianimal.py
  deeplabcut/utils/auxiliaryfunctions.py
  deeplabcut/utils/conversioncode.py
  deeplabcut/utils/visualization.py
  docs/recipes/BatchProcessing.md
  examples/testscript.py
  examples/testscript_multianimal.py
  tests/test_conversioncode.py
  tests/test_inferenceutils.py
  tests/test_pose_multianimal_imgaug.py
  tests/test_trainingsetmanipulation.py
  tests/test_video.py
Labels: enhancement

#1573 Optionally write data on the fly to a shelf during analyze_videos
  deeplabcut/pose_estimation_tensorflow/predict_multianimal.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/utils/auxfun_multianimal.py
Labels: enhancement

#1611 Backward compatibility of training on data stored the old way
  deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py
  deeplabcut/utils/conversioncode.py
Labels: bug fix!

#1614 Convert RGBA images to RGB if necessary
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/predict_multianimal.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/utils/auxfun_videos.py
Labels: bug fix!

#1567 Uniform analyze_videos API
  .gitignore
  deeplabcut/create_project/new.py
  deeplabcut/gui/analyze_videos.py
  deeplabcut/gui/create_videos.py
  deeplabcut/gui/extract_outlier_frames.py
  deeplabcut/gui/labeling_toolbox.py
  deeplabcut/gui/launch_script.py
  deeplabcut/gui/multiple_individuals_labeling_toolbox.py
  deeplabcut/gui/multiple_individuals_refinement_toolbox.py
  deeplabcut/gui/outlier_frame_extraction_toolbox.py
  deeplabcut/gui/refine_tracklets.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/post_processing/analyze_skeleton.py
  deeplabcut/post_processing/filtering.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/refine_training_dataset/stitch.py
  deeplabcut/utils/auxfun_multianimal.py
  deeplabcut/utils/auxiliaryfunctions.py
  deeplabcut/utils/make_labeled_video.py
  deeplabcut/utils/plotting.py
  docs/maDLC_UserGuide.md
  examples/COLAB/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb
  examples/testscript_multianimal.py
Labels: enhancement

#1615 Remove hardcoded path separators
  deeplabcut/utils/auxiliaryfunctions.py
Labels: enhancement

#1621 simplified 1-click maDLC analyze video, track, create video within the GUI
  deeplabcut/gui/analyze_videos.py
  deeplabcut/gui/create_new_project.py
  deeplabcut/gui/create_training_dataset.py
  deeplabcut/gui/create_videos.py
  deeplabcut/gui/evaluate_network.py
  deeplabcut/gui/extract_outlier_frames.py
  deeplabcut/gui/refine_tracklets.py
  deeplabcut/gui/train_network.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/utils/conversioncode.py
Labels: enhancement, GUI

#1622 Ignore numerical DataFrame index
  deeplabcut/utils/conversioncode.py
Labels: bug fix!

#1616 Update the model zoo Colab notebook
  deeplabcut/create_project/modelzoo.py
  examples/COLAB/COLAB_DLC_ModelZoo.ipynb
Labels: enhancement, bug fix!
