Repository DeepLabCut/DeepLabCut, pull requests merged in 2021-07, with the labels that each got.

#1381 Create videos with all detections from a folder path
  deeplabcut/gui/analyze_videos.py
  deeplabcut/utils/make_labeled_video.py
  docs/maDLC_UserGuide.md
Labels: bug fix!

#1383 allow making same splits (when creating the training-dataset) for multi-animal projects
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
Labels: enhancement

#1395 Keep counting iterations when retraining
  deeplabcut/pose_estimation_tensorflow/core/train.py
  deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py
  deeplabcut/pose_estimation_tensorflow/util/logging.py
Labels: enhancement

#1430 DLC 2.2 for macoS M1 chips
  conda-environments/DEEPLABCUT_M1.yaml
  docs/recipes/installTips.md
Labels: documentation, enhancement

#1427 Allow dlcrnet_ms5 with ResNet101/152
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
  examples/testscript_multianimal.py
Labels: new feature

#1437 Replace our current bug report template with new GitHub form
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#1444 Display all animals in the dataframe if none are found in the config
  deeplabcut/utils/plotting.py
Labels: bug fix!
