Repository DeepLabCut/DeepLabCut, pull requests merged in 2021-05, with the labels that each got.

#1209 2.2rc1 Documentation
  AUTHORS
  docs/README.md
  docs/installation.md
Labels: maDLC

#1213 Add options for assembly calibration & temporal cost to the GUI
  deeplabcut/gui/analyze_videos.py
  deeplabcut/gui/create_training_dataset.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
Labels: enhancement

#1220 Return 0 mAP when matching assemblies are not found
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
Labels: bug fix!

#1225 Force DataFrame to start at frame 0
  deeplabcut/refine_training_dataset/stitch.py
Labels: bug fix!

#1240 Consider user-defined output frame rate
  deeplabcut/utils/make_labeled_video.py
  deeplabcut/utils/video_processor.py
Labels: bug fix!

#1255 Update new.py
  deeplabcut/create_project/new.py
Labels: enhancement

#1264 Split path robustly when converting annotated data
  deeplabcut/utils/conversioncode.py
Labels: bug fix!

#1251 Smarter inclusion of identity information and tests
  deeplabcut/gui/analyze_videos.py
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/refine_training_dataset/stitch.py
  docs/maDLC_UserGuide.md
  tests/conftest.py
  tests/data/trimouse_tracklets.pickle
  tests/test_inferenceutils.py
  tests/test_stitcher.py
  tests/test_trackingutils.py
Labels: enhancement

#1274 Do not alter original config dictionary
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
Labels: bug fix!

#1273 Check for the addition of new animals to the config while labeling
  deeplabcut/gui/multiple_individuals_labeling_toolbox.py
Labels: enhancement
