Repository DeepLabCut/DeepLabCut, pull requests merged in 2022-03, with the labels that each got.

#1711 Discard empty assemblies but not those without links
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
  tests/test_inferenceutils.py
Labels: bug fix!

#1674 Drop smart crop aug parameters from single-animal pose_cfg
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
Labels: enhancement

#1607 Randomly prune large graphs
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
  deeplabcut/utils/auxfun_multianimal.py
  tests/test_auxfun_multianimal.py
Labels: enhancement

#1660 adds frame extraction to add_new_videos
  deeplabcut/create_project/add.py
  deeplabcut/generate_training_dataset/frame_extraction.py
Labels: enhancement

#1731 Minor create_labeled_video refactoring
  deeplabcut/utils/make_labeled_video.py
Labels: enhancement

#1738 Exit while loop prematurely if not finding valid image sizes
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
Labels: bug fix!

#1737 Add test time image resizing
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  tests/test_pose_multianimal_imgaug.py
Labels: enhancement

#1686 OpenVINO backend
  _toc.yml
  deeplabcut/pose_estimation_tensorflow/core/openvino/__init__.py
  deeplabcut/pose_estimation_tensorflow/core/openvino/mo_extensions/__init__.py
  deeplabcut/pose_estimation_tensorflow/core/openvino/mo_extensions/front/__init__.py
  deeplabcut/pose_estimation_tensorflow/core/openvino/mo_extensions/front/tf/__init__.py
  deeplabcut/pose_estimation_tensorflow/core/openvino/mo_extensions/front/tf/unravel_index.py
  deeplabcut/pose_estimation_tensorflow/core/openvino/session.py
  deeplabcut/pose_estimation_tensorflow/core/predict.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  docs/recipes/OpenVINO.md
  setup.py
Labels: enhancement, tensorflow/training
