Repository DeepLabCut/DeepLabCut, pull requests merged in 2022-12, with the labels that each got.

#2076 Move Hugging Face's pre-trained weights to the right target directory
  deeplabcut/utils/auxfun_models.py
Labels: bug fix!

#2014 Added inference code for incoming SuperAnimal models
  _toc.yml
  deeplabcut/__init__.py
  deeplabcut/pose_estimation_tensorflow/__init__.py
  deeplabcut/pose_estimation_tensorflow/predict_supermodel.py
  deeplabcut/pose_estimation_tensorflow/superanimal_configs/superquadruped.yaml
  deeplabcut/pose_estimation_tensorflow/superanimal_configs/supertopview.yaml
  deeplabcut/utils/make_labeled_video.py
  docs/ModelZoo.md
  docs/api/deeplabcut.video_inference_superanimal.rst
  examples/testscript_superanimal_inference.py
  tests/test_predict_supermodel.py
Labels: ModelZoo

#2077 Fix matched frame extraction for 3d projects
  deeplabcut/generate_training_dataset/frame_extraction.py
Labels: bug fix!

#2087 Cap TF version to 2.10
  setup.py
Labels: Installation

#2089 Update branch name to "main" in GitHub's CI workflow
  .github/workflows/python-package.yml
  requirements.txt
Labels: bug fix!

#2085 Fix "merge datasets" button action
  deeplabcut/gui/tabs/extract_outlier_frames.py
Labels: GUI, bug fix!

#2063 Do not add a new video if it already exists
  deeplabcut/create_project/add.py
Labels: bug fix!

#2091 prevents replotting of existing plots during model evaluation
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
Labels: enhancement

#2103 Minor COLAB modelzoo improvements
  deeplabcut/create_project/modelzoo.py
  examples/COLAB/COLAB_DLC_ModelZoo.ipynb
Labels: enhancement

#2078 Video adaptation api
  .github/workflows/python-package.yml
  deeplabcut/generate_training_dataset/frame_extraction.py
  deeplabcut/gui/tabs/__init__.py
  deeplabcut/gui/tabs/modelzoo.py
  deeplabcut/gui/window.py
  deeplabcut/modelzoo/__init__.py
  deeplabcut/modelzoo/apis/__init__.py
  deeplabcut/modelzoo/apis/spatiotemporal_adapt.py
  deeplabcut/modelzoo/models.json
  deeplabcut/modelzoo/utils.py
  deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/predict_supermodel.py
  deeplabcut/pose_estimation_tensorflow/superanimal_configs/superquadruped.yaml
  deeplabcut/pose_estimation_tensorflow/superanimal_configs/supertopview.yaml
  deeplabcut/utils/make_labeled_video.py
  examples/COLAB/COLAB_DEMO_SuperAnimal.ipynb
  requirements.txt
  setup.py
  tools/README.md
  tools/update_license_headers.py
Labels: enhancement

#2105 improve model zoo install and docs
  docs/ModelZoo.md
  docs/PROJECT_GUI.md
  docs/installation.md
  examples/COLAB/COLAB_DLC_ModelZoo.ipynb
Labels: Installation, documentation, ModelZoo
