Repository DeepLabCut/DeepLabCut, pull requests merged in 2022-01, with the labels that each got.

#1628 drop opencv
  requirements.txt
  setup.py
Labels: Installation, COLAB

#1632 DLC v2.2.0.4 release
  deeplabcut/create_project/add.py
  deeplabcut/create_project/demo_data.py
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/gui/outlier_frame_extraction_toolbox.py
  deeplabcut/pose_estimation_tensorflow/backbones/efficientnet_model.py
  deeplabcut/pose_estimation_tensorflow/backbones/mobilenet.py
  deeplabcut/pose_estimation_tensorflow/backbones/mobilenet_v2.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/core/predict.py
  deeplabcut/pose_estimation_tensorflow/core/predict_multianimal.py
  deeplabcut/pose_estimation_tensorflow/core/train.py
  deeplabcut/pose_estimation_tensorflow/datasets/augmentation.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/utils.py
  deeplabcut/pose_estimation_tensorflow/export.py
  deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
  deeplabcut/pose_estimation_tensorflow/lib/trackingutils.py
  deeplabcut/pose_estimation_tensorflow/nnets/base.py
  deeplabcut/pose_estimation_tensorflow/nnets/conv_blocks.py
  deeplabcut/pose_estimation_tensorflow/nnets/layers.py
  deeplabcut/pose_estimation_tensorflow/nnets/mobilenet.py
  deeplabcut/pose_estimation_tensorflow/nnets/multi.py
  deeplabcut/pose_estimation_tensorflow/nnets/resnet.py
  deeplabcut/pose_estimation_tensorflow/predict_multianimal.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/pose_estimation_tensorflow/training.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/refine_training_dataset/stitch.py
  deeplabcut/utils/auxfun_videos.py
  deeplabcut/utils/skeleton.py
  deeplabcut/version.py
  examples/test.sh
  examples/testM1.sh
  examples/testscript.py
  examples/testscript_multianimal.py
  examples/testscript_openfielddata_augmentationcomparison.py
  examples/testscript_openfielddata_netcomparison.py
  reinstall.sh
  setup.py
  tests/test_trainingsetmanipulation.py
Labels: enhancement

#1634 Easily mine tracklets from the TrackletStitcher
  deeplabcut/refine_training_dataset/stitch.py
Labels: enhancement

#1633 Backwards compat., allowing track_method in conv2tracklets and stitching
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/refine_training_dataset/stitch.py
  deeplabcut/utils/auxfun_multianimal.py
  deeplabcut/version.py
  examples/test.sh
  examples/testM1.sh
  examples/testscript_multianimal.py
  reinstall.sh
  setup.py
Labels: backwards compatibility

#1641 Properly handle empty assemblies
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
Labels: bug fix!

#1647 Fix merge of old and new (path agnostic) DataFrames
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/utils/conversioncode.py
Labels: bug fix!

#1653 Fix for restarted training not following the lr schedule
  deeplabcut/pose_estimation_tensorflow/core/train.py
  deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py
Labels: bug fix!

#1657 Introduce DLC <-> NWB data conversion
  deeplabcut/__init__.py
  deeplabcut/gui/analyze_videos.py
  deeplabcut/utils/conversioncode.py
Labels: enhancement

#1652 Set confidence to 0 when instantiating Assembly
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
Labels: bug fix!
