Repository DeepLabCut/DeepLabCut, pull requests merged in 2023-10, with the labels that each got.

#2402 Bump python to 3.9 in DEEPLABCUT.yaml environment file
  conda-environments/DEEPLABCUT.yaml
Labels: enhancement

#2396 Address underlying compatibility issue with scipy 1.11.0
  deeplabcut/refine_training_dataset/stitch.py
  requirements.txt
  setup.py
Labels: backwards compatibility

#2399 Unifying docs on Napari DeepLabCut
  docs/napariGUI.md
Labels: documentation

#2404 Update publish-book.yml
  .github/workflows/publish-book.yml
  _toc.yml
  docs/napari_GUI.md
Labels: backwards compatibility

#1908 "deeplabcut.filterpredictions" and "deeplabcut.analyze_skeleton" return mappings
  deeplabcut/post_processing/analyze_skeleton.py
  deeplabcut/post_processing/filtering.py
Labels: enhancement

#2414 Let user change the search window size during corner detection refinement
  deeplabcut/pose_estimation_3d/camera_calibration.py
Labels: enhancement

#2422 Automatically check for napari-deeplabcut updates (in addition to DLC)
  deeplabcut/gui/window.py
  setup.py
Labels: enhancement

#2426 Smartly restore pretrained model weights
  deeplabcut/pose_estimation_tensorflow/core/train.py
  deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py
  deeplabcut/utils/auxfun_models.py
Labels: enhancement
