Repository DeepLabCut/DeepLabCut, pull requests merged in 2023-06, with the labels that each got.

#2270 Fix deprecated numpy builtin type
  deeplabcut/pose_estimation_tensorflow/core/predict_multianimal.py
  deeplabcut/pose_estimation_tensorflow/lib/trackingutils.py
  deeplabcut/utils/frameselectiontools.py
Labels: bug fix!

#2272 Pass train/test indices to create_multianimaltraining_dataset
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
Labels: bug fix!

#2290 pin scipy to less than 1.11.0
  requirements.txt
  setup.py
Labels: dependencies

#2288 Fixed draw_bbox when pyplot is in non-interactive mode
  deeplabcut/utils/auxfun_videos.py
Labels: bug fix!

#2291 Bug fix spatiotemporal adaptation kwargs
  deeplabcut/modelzoo/api/spatiotemporal_adapt.py
Labels: bug fix!

#2294 Update README.md
  README.md
Labels: documentation

#2287 Avoid creating training dataset with multiple scorers
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
Labels: enhancement
