Repository DeepLabCut/DeepLabCut, pull requests merged in 2023-07, with the labels that each got.

#2315 Add function to get per-bodypart RMSE
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  examples/testscript.py
  examples/testscript_multianimal.py
  tests/test_evaluate.py
Labels: enhancement

#2275 Some usability improvements to the main GUI
  deeplabcut/generate_training_dataset/frame_extraction.py
  deeplabcut/gui/tabs/create_project.py
  deeplabcut/gui/tabs/create_training_dataset.py
  deeplabcut/gui/tabs/extract_frames.py
  deeplabcut/gui/tabs/extract_outlier_frames.py
  deeplabcut/gui/tabs/label_frames.py
  deeplabcut/gui/tabs/video_editor.py
  deeplabcut/gui/widgets.py
  deeplabcut/gui/window.py
  setup.py
Labels: enhancement, GUI

#2320 fix broken gputouse
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/utils/auxfun_models.py
Labels: WORK IN PROGRESS!, high-priority

#2317 Avoid assembling if already done and overwrite == False
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
Labels: WORK IN PROGRESS!, high-priority
