Repository DeepLabCut/DeepLabCut, pull requests merged in 2023-05, with the labels that each got.

#2223 Fetch mice demo data from Zenodo
  examples/COLAB/COLAB_3miceDemo.ipynb
Labels: backwards compatibility

#2233 Fix randomly failing multi-animal test script
  examples/testscript_multianimal.py
Labels: enhancement

#2241 Basicformatting
  deeplabcut/cli.py
  deeplabcut/generate_training_dataset/frame_extraction.py
  deeplabcut/gui/components.py
  deeplabcut/gui/tabs/analyze_videos.py
  deeplabcut/gui/tabs/create_project.py
  deeplabcut/gui/tabs/create_videos.py
  deeplabcut/gui/tabs/evaluate_network.py
  deeplabcut/gui/tabs/extract_frames.py
  deeplabcut/gui/tabs/extract_outlier_frames.py
  deeplabcut/gui/tabs/refine_tracklets.py
  deeplabcut/gui/tabs/train_network.py
  deeplabcut/gui/tabs/video_editor.py
  deeplabcut/gui/tracklet_toolbox.py
  deeplabcut/gui/window.py
  deeplabcut/modelzoo/api/spatiotemporal_adapt.py
  deeplabcut/modelzoo/api/superanimal_inference.py
  deeplabcut/pose_estimation_3d/plotting3D.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/core/predict_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py
  deeplabcut/pose_estimation_tensorflow/nnets/multi.py
  deeplabcut/pose_estimation_tensorflow/predict_multianimal.py
  deeplabcut/pose_tracking_pytorch/apis.py
  deeplabcut/pose_tracking_pytorch/create_dataset.py
  deeplabcut/pose_tracking_pytorch/datasets/dlc_vec.py
  deeplabcut/pose_tracking_pytorch/inference.py
  deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py
  deeplabcut/pose_tracking_pytorch/model/make_model.py
  deeplabcut/pose_tracking_pytorch/processor/processor.py
  deeplabcut/pose_tracking_pytorch/tracking_utils/preprocessing.py
  deeplabcut/pose_tracking_pytorch/tracking_utils/reranking.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/utils/auxfun_multianimal.py
  deeplabcut/utils/frameselectiontools.py
  examples/testscript_multianimal.py
  examples/testscript_transreid.py
  tests/test_auxiliaryfunctions.py
  tests/test_dataset_augmentation.py
  tests/test_frame_selection_tools.py
Labels: documentation

#2247 Update use of .Directory for PySide6.5.0
  deeplabcut/gui/tabs/label_frames.py
Labels: GUI

#2198 Additions to modelzoo APIs
  deeplabcut/modelzoo/api/spatiotemporal_adapt.py
  deeplabcut/modelzoo/api/superanimal_inference.py
  deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/predict_supermodel.py
  examples/testscript_superanimal_adaptation.py
Labels: ModelZoo

#2255 Update setup.py, docs
  docs/PROJECT_GUI.md
  docs/napariGUI.md
  setup.py
Labels: documentation
