Repository DeepLabCut/DeepLabCut, pull requests merged in 2023-11, with the labels that each got.

#2389 Shaokai/sa transfer learning
  deeplabcut/generate_training_dataset/frame_extraction.py
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/gui/tabs/extract_frames.py
  deeplabcut/gui/tracklet_toolbox.py
  deeplabcut/gui/window.py
  deeplabcut/modelzoo/api/spatiotemporal_adapt.py
  deeplabcut/modelzoo/api/superanimal_inference.py
  deeplabcut/pose_estimation_tensorflow/core/train_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
  deeplabcut/pose_estimation_tensorflow/nnets/utils.py
  deeplabcut/pose_estimation_tensorflow/predict_supermodel.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/pose_estimation_tensorflow/training.py
  deeplabcut/pose_estimation_tensorflow/util/visualize.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py
  deeplabcut/pose_tracking_pytorch/solver/cosine_lr.py
  deeplabcut/pose_tracking_pytorch/tracking_utils/reranking.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/refine_training_dataset/stitch.py
  deeplabcut/utils/make_labeled_video.py
  docs/ModelZoo.md
  examples/testscript_superanimal_transfer_learning.py
  setup.py
  tests/test_dataset_augmentation.py
  tests/test_inferenceutils.py
Labels: enhancement, ModelZoo

#2431 Improvements to the model zoo's GUI tab
  deeplabcut/gui/tabs/modelzoo.py
Labels: enhancement

#2436 Fix video adaptation
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/predict_supermodel.py
Labels: bug fix!

#2440 Pull demo data from Zenodo
  examples/COLAB/COLAB_transformer_reID.ipynb
Labels: bug fix!
