Repository DeepLabCut/DeepLabCut, pull requests merged in 2023-02, with the labels that each got.

#2131 Add warning message during calibration when no complete poses are found
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
Labels: enhancement

#2122 extracted defs from main functions
  deeplabcut/benchmark/metrics.py
Labels: benchmark API

#2096 Label video when num_outputs > 1 (and overwriting flag)
  deeplabcut/utils/make_labeled_video.py
Labels: enhancement

#2147 Fix keypoint location in create_labeled_video after cropped analysis
  deeplabcut/utils/make_labeled_video.py
Labels: bug fix!

#2148 Fix typo in argument given to GUI's deeplabcut.filterpredictions
  deeplabcut/gui/tabs/analyze_videos.py
Labels: bug fix!
