Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-07, with the labels that each got.

#2650 Fix OSError: Could not find a backend to open `CollectedData_Alex.csv` with iomode `r`
  examples/testscript.py
Labels: bug fix!

#2508 Add feature to evaluate network for specfic, named snapshots.
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/export.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/utils/auxiliaryfunctions.py
  examples/testscript.py
  tests/test_auxiliaryfunctions.py
  tests/test_evaluate.py
Labels: enhancement, high-priority

#2645 fixed file dialog not showing uppercase file extension video files
  deeplabcut/gui/components.py
Labels: GUI

#2673 Fix video extension filter in filterpredictions
  deeplabcut/utils/auxiliaryfunctions.py
Labels: bug fix!, DLC3.0🔥

#2653 Fix and decouple video rotation from other operations
  deeplabcut/gui/tabs/video_editor.py
  deeplabcut/utils/auxfun_videos.py
Labels: bug fix!, DLC3.0🔥

#2657 merge named snapshot evaluation into pytorch_dlc
  deeplabcut/compat.py
  deeplabcut/gui/components.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/export.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/utils/auxiliaryfunctions.py
  examples/testscript.py
  tests/test_auxiliaryfunctions.py
  tests/test_evaluate.py
Labels: DLC3.0🔥

#2672 Handle internet connectivity issues
  deeplabcut/gui/window.py
Labels: bug fix!, DLC3.0🔥

#2629 New PyTorch DeepLabCut SuperAnimal demo notebook
  deeplabcut/modelzoo/generalized_data_converter/datasets/base.py
  deeplabcut/modelzoo/generalized_data_converter/datasets/materialize.py
  deeplabcut/pose_estimation_pytorch/apis/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_images.py
  deeplabcut/pose_estimation_pytorch/apis/train.py
  deeplabcut/pose_estimation_pytorch/config/base/base.yaml
  deeplabcut/pose_estimation_pytorch/modelzoo/memory_replay.py
  deeplabcut/utils/pseudo_label.py
  examples/COLAB/COLAB_YOURDATA_SuperAnimal.ipynb
Labels: ModelZoo, DLC3.0🔥

#2668 Update train.py: avoids error on 'unique_bodyparts'
  deeplabcut/pose_estimation_pytorch/runners/train.py
Labels: DLC3.0🔥

#2676 New detector options and better detector integration
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/gui/tabs/create_training_dataset.py
  deeplabcut/pose_estimation_pytorch/__init__.py
  deeplabcut/pose_estimation_pytorch/config/__init__.py
  deeplabcut/pose_estimation_pytorch/config/detectors/fasterrcnn_mobilenet_v3_large_fpn.yaml
  deeplabcut/pose_estimation_pytorch/config/detectors/fasterrcnn_resnet50_fpn_v2.yaml
  deeplabcut/pose_estimation_pytorch/config/detectors/ssdlite.yaml
  deeplabcut/pose_estimation_pytorch/config/make_pose_config.py
  deeplabcut/pose_estimation_pytorch/config/utils.py
  deeplabcut/pose_estimation_pytorch/models/detectors/__init__.py
  deeplabcut/pose_estimation_pytorch/models/detectors/fasterRCNN.py
  deeplabcut/pose_estimation_pytorch/models/detectors/ssd.py
  deeplabcut/pose_estimation_pytorch/models/detectors/torchvision.py
  tests/pose_estimation_pytorch/config/test_make_pose_config.py
Labels: DLC3.0🔥

#2681 backwards compatibility
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
Labels: bug fix!, DLC3.0🔥
