Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-10, with the labels that each got.

#2747 pytorch_dlc - Small updates and bug fixes
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/apis/evaluate.py
  deeplabcut/pose_estimation_pytorch/config/base/detector.yaml
  deeplabcut/pose_estimation_pytorch/config/base/head_bodyparts.yaml
  deeplabcut/pose_estimation_pytorch/config/base/head_bodyparts_with_paf.yaml
  deeplabcut/pose_estimation_pytorch/config/base/head_identity.yaml
  deeplabcut/pose_estimation_pytorch/config/base/head_topdown.yaml
  deeplabcut/pose_estimation_pytorch/config/dekr/dekr_w18.yaml
  deeplabcut/pose_estimation_pytorch/config/dekr/dekr_w32.yaml
  deeplabcut/pose_estimation_pytorch/config/dekr/dekr_w48.yaml
  deeplabcut/pose_estimation_pytorch/models/predictors/paf_predictor.py
  deeplabcut/pose_estimation_pytorch/models/target_generators/heatmap_targets.py
  deeplabcut/pose_estimation_pytorch/models/target_generators/pafs_targets.py
  deeplabcut/pose_estimation_pytorch/runners/logger.py
  docs/pytorch/pytorch_config.md
  tests/pose_estimation_pytorch/runners/test_logger.py
Labels: DLC3.0🔥

#2761 Update standardDeepLabCut_UserGuide.md
  docs/standardDeepLabCut_UserGuide.md
Labels: documentation

#2763 Look for uppercase video extensions when creating projects
  deeplabcut/create_project/new.py
  deeplabcut/gui/tabs/create_project.py
Labels: DLC3.0🔥

#2767 Create citation.md
  README.md
  _toc.yml
  docs/citation.md
Labels: enhancement, documentation
