Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-03, with the labels that each got.

#2525 Avoid infinite loop in `mine()` when there are no overlapping tracklets
  deeplabcut/refine_training_dataset/stitch.py
Labels: bug fix!

#2527 fix manual frame extraction with symlinks
  deeplabcut/gui/tabs/extract_frames.py
Labels: GUI, bug fix!

#2532 Adding a Quick Guide (from the wiki to the docs!)
  _toc.yml
  docs/single_animal_quick_guide.md
  tutorial_maDLC.md
Labels: documentation
