Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-08, with the labels that each got.

#2707 Identity Predictor
  deeplabcut/pose_estimation_pytorch/config/base/head_identity.yaml
  deeplabcut/pose_estimation_pytorch/models/predictors/__init__.py
  deeplabcut/pose_estimation_pytorch/models/predictors/identity_predictor.py
Labels: DLC3.0🔥

#2708 batched inference
  deeplabcut/compat.py
  deeplabcut/create_project/new.py
  deeplabcut/modelzoo/video_inference.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/modelzoo/inference.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
  deeplabcut/utils/auxiliaryfunctions.py
  tests/pose_estimation_pytorch/runners/test_runners_inference.py
Labels: DLC3.0🔥

#2709 Bug fixes: `find_closest_neighbors` + ellipse tracking
  deeplabcut/core/crossvalutils.py
  deeplabcut/core/trackingutils.py
Labels: DLC3.0🔥

#2680 Swap button added to the track refinement GUI
  deeplabcut/benchmark/base.py
  deeplabcut/benchmark/metrics.py
  deeplabcut/create_project/new.py
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
  deeplabcut/gui/tabs/extract_frames.py
  deeplabcut/gui/tabs/modelzoo.py
  deeplabcut/gui/tracklet_toolbox.py
  deeplabcut/gui/window.py
  deeplabcut/modelzoo/api/superanimal_inference.py
  deeplabcut/pose_estimation_3d/camera_calibration.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_base.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py
  deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py
  deeplabcut/pose_estimation_tensorflow/nnets/base.py
  deeplabcut/pose_estimation_tensorflow/nnets/utils.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/pose_estimation_tensorflow/training.py
  deeplabcut/pose_estimation_tensorflow/util/visualize.py
  deeplabcut/pose_estimation_tensorflow/vis_dataset.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py
  deeplabcut/pose_tracking_pytorch/solver/cosine_lr.py
  deeplabcut/pose_tracking_pytorch/tracking_utils/reranking.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/refine_training_dataset/stitch.py
  deeplabcut/refine_training_dataset/tracklets.py
  deeplabcut/utils/auxfun_models.py
  deeplabcut/utils/conversioncode.py
  deeplabcut/utils/make_labeled_video.py
  dlc.py
  examples/testscript.py
  tests/test_auxfun_models.py
  tests/test_auxiliaryfunctions.py
  tests/test_crossvalutils.py
  tests/test_dataset_augmentation.py
  tests/test_evaluate.py
  tests/test_inferenceutils.py
  tests/test_pose_multianimal_imgaug.py
Labels: enhancement, maDLC

#2443 Fixes for testscript_3d.py
  examples/stereo_example.zip
  examples/testscript_3d.py
Labels: 3D, high-priority

#2717 bug fix: find closest neighbors
  deeplabcut/core/crossvalutils.py
Labels: bug fix!, DLC3.0🔥

#2713 Minimal backward compatibility
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
Labels: backwards compatibility

#2714 Documentation Improvements - DeepLabCut PyTorch Code
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/README.md
  deeplabcut/pose_estimation_pytorch/apis/train.py
  deeplabcut/pose_estimation_pytorch/config/base/base.yaml
  deeplabcut/pose_estimation_pytorch/config/make_pose_config.py
  deeplabcut/pose_estimation_pytorch/config/utils.py
  deeplabcut/pose_estimation_pytorch/data/dlcloader.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
  deeplabcut/utils/auxfun_multianimal.py
  deeplabcut/utils/pseudo_label.py
Labels: documentation, DLC3.0🔥

#2701 Allow processing of videos in MKV containers
  deeplabcut/gui/dlc_params.py
  docs/beginner-guides/beginners-guide.md
  docs/beginner-guides/video-analysis.md
Labels: enhancement
