Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-12, with the labels that each got.

#2799 Model Output Visualization for PyTorch Models
  deeplabcut/compat.py
  deeplabcut/core/visualization.py
  deeplabcut/modelzoo/model_configs/fasterrcnn_mobilenet_v3_large_fpn.yaml
  deeplabcut/modelzoo/model_configs/fasterrcnn_resnet50_fpn_v2.yaml
  deeplabcut/modelzoo/model_configs/ssdlite.yaml
  deeplabcut/pose_estimation_pytorch/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/train.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/apis/visualization.py
  deeplabcut/pose_estimation_pytorch/data/base.py
  deeplabcut/pose_estimation_pytorch/data/dlcloader.py
  deeplabcut/pose_estimation_pytorch/models/model.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  docs/pytorch/user_guide.md
Labels: DLC3.0🔥

#2792 Add Functions for Visualizing COCO Predictions and Ground Truth
  deeplabcut/pose_estimation_pytorch/apis/evaluate.py
Labels: DLC3.0🔥

#2800 DLC 3.0 - Function to export PyTorch models
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/apis/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/export.py
  deeplabcut/pose_estimation_pytorch/data/dlcloader.py
  docs/pytorch/user_guide.md
  tests/pose_estimation_pytorch/apis/test_apis_export.py
Labels: enhancement, DLC3.0🔥

#2805 Fix version check timeout
  deeplabcut/gui/window.py
  tests/gui/test_gui_window.py
Labels: GUI

#2813 Prune PAF graphs before evaluation
  deeplabcut/pose_estimation_pytorch/apis/evaluate.py
  deeplabcut/pose_estimation_pytorch/apis/prune_paf_graph.py
  deeplabcut/pose_estimation_pytorch/data/__init__.py
  deeplabcut/pose_estimation_pytorch/models/predictors/paf_predictor.py
  deeplabcut/pose_estimation_pytorch/models/predictors/utils.py
Labels: enhancement, DLC3.0🔥

#2791 Plot detector's bboxes if Top-Down architecture
  deeplabcut/compat.py
  deeplabcut/modelzoo/video_inference.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/apis/evaluate.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/modelzoo/inference.py
  deeplabcut/utils/auxiliaryfunctions.py
  deeplabcut/utils/make_labeled_video.py
  deeplabcut/utils/visualization.py
Labels: enhancement, DLC3.0🔥

#2817 Update `superanimal_analyze_images` plotting
  deeplabcut/pose_estimation_pytorch/apis/analyze_images.py
  deeplabcut/pose_estimation_pytorch/apis/visualization.py
Labels: DLC3.0🔥

#2818 Set `weights_only=True` as a default when loading snapshot weights.
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/runners/base.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
  deeplabcut/pose_estimation_pytorch/runners/train.py
  tests/pose_estimation_pytorch/modelzoo/test_load_superanimal_models.py
  tests/pose_estimation_pytorch/runners/test_runners.py
  tests/pose_estimation_pytorch/runners/test_runners_inference.py
  tests/pose_estimation_pytorch/runners/test_runners_train.py
Labels: enhancement, DLC3.0🔥

#2816 Implement missing arguments for PyTorch models
  deeplabcut/__init__.py
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_images.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py
  deeplabcut/pose_estimation_pytorch/apis/train.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/runners/__init__.py
  deeplabcut/pose_estimation_pytorch/runners/base.py
  deeplabcut/pose_estimation_pytorch/runners/dynamic_cropping.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
  deeplabcut/pose_estimation_pytorch/runners/train.py
  docs/pytorch/user_guide.md
  tests/pose_estimation_pytorch/runners/test_dynamic_cropper.py
  tests/pose_estimation_pytorch/runners/test_runners_inference.py
  tests/pose_estimation_pytorch/runners/test_runners_train.py
Labels: DLC3.0🔥

#2819 Add missing positional arguments to SuperAnimal Colab
  examples/COLAB/COLAB_DEMO_SuperAnimal.ipynb
Labels: COLAB, DLC3.0🔥

#2814 SuperAnimal demo colab update (for DLC3)
  examples/COLAB/COLAB_DEMO_SuperAnimal.ipynb
Labels: COLAB, DLC3.0🔥
