Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-06, with the labels that each got.

#2586 Update label and warn users of the absence of videos
  deeplabcut/gui/tabs/extract_frames.py
Labels: enhancement, GUI

#2583 pin matplotlib version
  setup.py
Labels: Another package code issue

#2599 Fix 2d line data setter
  deeplabcut/utils/visualization.py
Labels: bug fix!

#2600 Auto check for dlclibrary & napari-deeplabcut updates when the GUI opens
  deeplabcut/gui/window.py
Labels: enhancement

#2614 python 3.10 is required
  conda-environments/DEEPLABCUT_M1.yaml
  docs/installation.md
Labels: backwards compatibility, documentation, dependencies

#2605 Add PyTorch🔥 documentation
  .github/workflows/codespell.yml
  .github/workflows/python-package.yml
  AUTHORS
  README.md
  _toc.yml
  conda-environments/DEEPLABCUT.yaml
  docs/ModelZoo.md
  docs/Overviewof3D.md
  docs/UseOverviewGuide.md
  docs/beginner-guides/Training-Evaluation.md
  docs/beginner-guides/beginners-guide.md
  docs/beginner-guides/labeling.md
  docs/beginner-guides/manage-project.md
  docs/beginner-guides/video-analysis.md
  docs/beginners-guide.md
  docs/course.md
  docs/gui/PROJECT_GUI.md
  docs/gui/napari_GUI.md
  docs/installation.md
  docs/intro.md
  docs/maDLC_UserGuide.md
  docs/pytorch/architectures.md
  docs/pytorch/pytorch_config.md
  docs/pytorch/user_guide.md
  docs/quick-start/single_animal_quick_guide.md
  docs/quick-start/tutorial_maDLC.md
  docs/standardDeepLabCut_UserGuide.md
Labels: documentation, DLC3.0🔥

#2622 Fix PySide6 AttributeError and uninitialized variable
  deeplabcut/gui/window.py
  deeplabcut/utils/frameselectiontools.py
Labels: bug fix!

#2633 Fix video overwrite
  deeplabcut/gui/tabs/create_videos.py
Labels: bug fix!
