Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-09, with the labels that each got.

#2731 merge `main` into `pytorch_dlc`
  deeplabcut/benchmark/base.py
  deeplabcut/benchmark/metrics.py
  deeplabcut/create_project/new.py
  deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py
  deeplabcut/gui/dlc_params.py
  deeplabcut/gui/tabs/extract_frames.py
  deeplabcut/gui/tracklet_toolbox.py
  deeplabcut/pose_estimation_3d/camera_calibration.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate.py
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_base.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py
  deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py
  deeplabcut/pose_estimation_tensorflow/nnets/base.py
  deeplabcut/pose_estimation_tensorflow/nnets/utils.py
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/pose_estimation_tensorflow/training.py
  deeplabcut/pose_estimation_tensorflow/util/visualize.py
  deeplabcut/pose_estimation_tensorflow/vis_dataset.py
  deeplabcut/pose_estimation_tensorflow/visualizemaps.py
  deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py
  deeplabcut/pose_tracking_pytorch/solver/cosine_lr.py
  deeplabcut/pose_tracking_pytorch/tracking_utils/reranking.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/refine_training_dataset/stitch.py
  deeplabcut/refine_training_dataset/tracklets.py
  deeplabcut/utils/auxfun_models.py
  deeplabcut/utils/conversioncode.py
  deeplabcut/utils/make_labeled_video.py
  dlc.py
  docs/beginner-guides/beginners-guide.md
  docs/beginner-guides/video-analysis.md
  examples/stereo_example.zip
  examples/testscript.py
  examples/testscript_3d.py
  tests/test_auxfun_models.py
  tests/test_auxiliaryfunctions.py
  tests/test_crossvalutils.py
  tests/test_dataset_augmentation.py
  tests/test_evaluate.py
  tests/test_inferenceutils.py
  tests/test_pose_multianimal_imgaug.py
Labels: DLC3.0🔥

#2735 add in CZI EOSS badge and funding section
  README.md
Labels: documentation

#2718 Fix minimalnumberofconnections
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
Labels: maDLC

#2716 Benchmarking user guide
  _toc.yml
  docs/pytorch/Benchmarking_shuffle_guide.md
  docs/pytorch/assets/img1.png
  docs/pytorch/assets/img2.png
  docs/pytorch/assets/img3.png
  docs/pytorch/assets/img4.png
  docs/pytorch/assets/img5.png
Labels: documentation, DLC3.0🔥

#2729 Make 3D Triangulate possible with pytorch_dlc branch and MA project
  deeplabcut/pose_estimation_3d/triangulation.py
  deeplabcut/utils/auxiliaryfunctions_3d.py
Labels: 3D, DLC3.0🔥

#2740 Data compatibility - Benchmark
  deeplabcut/benchmark/__init__.py
  deeplabcut/benchmark/base.py
  deeplabcut/benchmark/benchmarks.py
Labels: DLC3.0🔥

#2737 Adding cropping to pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/utils/auxfun_videos.py
Labels: DLC3.0🔥
