Repository DeepLabCut/DeepLabCut, pull requests merged in 2024-11, with the labels that each got.

#2774 Resume training from existing snapshots option in GUI
  deeplabcut/gui/components.py
  deeplabcut/gui/tabs/train_network.py
  deeplabcut/gui/window.py
Labels: GUI, DLC3.0🔥

#2778 Fix failing DLC 3.0 tests - changes to internal implementation
  tests/pose_estimation_pytorch/modelzoo/test_webapp.py
  tests/pose_estimation_pytorch/other/test_dataset.py
Labels: DLC3.0🔥

#2785 Video Analysis with Identity - Lowering memory footprint
  deeplabcut/pose_estimation_pytorch/config/make_pose_config.py
  deeplabcut/pose_estimation_pytorch/data/postprocessor.py
  deeplabcut/pose_estimation_pytorch/post_processing/identity.py
  tests/pose_estimation_pytorch/data/test_postprocessor.py
Labels: enhancement, DLC3.0🔥

#2782 Timeout retrieving latest package version from the Web
  deeplabcut/gui/utils.py
  deeplabcut/gui/window.py
Labels: DLC3.0🔥

#2788 Load scheduler state when resuming training
  deeplabcut/pose_estimation_pytorch/runners/base.py
  deeplabcut/pose_estimation_pytorch/runners/schedulers.py
  deeplabcut/pose_estimation_pytorch/runners/train.py
  docs/pytorch/pytorch_config.md
  tests/pose_estimation_pytorch/other/test_schedulers.py
  tests/pose_estimation_pytorch/runners/test_runners_train.py
  tests/pose_estimation_pytorch/runners/test_schedulers.py
Labels: enhancement, DLC3.0🔥

#2793 Fix: correct the early return error when save_epochs=1 and optimize the clean up way
  deeplabcut/pose_estimation_pytorch/runners/snapshots.py
Labels: DLC3.0🔥
