Repository DeepLabCut/DeepLabCut, pull requests merged in 2025-05, with the labels that each got.

#2978 Clarify the CTD evaluation conditions and fix the variable reference used for URL access
  examples/COLAB/COLAB_BUCTD_and_CTD_tracking.ipynb
Labels: COLAB, bug fix!, DLC3.0🔥

#2979 Fix BUCTD Colab link
  docs/maDLC_UserGuide.md
Labels: documentation

#2972 Remove duplicate dlclibrary specification in the setup.py
  setup.py
Labels: dependencies

#2984 Improve CTD preprocessors pipeline
  deeplabcut/pose_estimation_pytorch/data/preprocessor.py
  deeplabcut/pose_estimation_pytorch/data/utils.py
  tests/pose_estimation_pytorch/data/test_preprocessor.py
Labels: bug fix!, DLC3.0🔥, CTD
