Repository DeepLabCut/DeepLabCut, pull requests merged in 2025-03, with the labels that each got.

#2915 Fix testscript_superanimal_create_pretrained_project
  examples/testscript_superanimal_create_pretrained_project.py
Labels: bug fix!, ModelZoo, DLC3.0🔥

#2917 Fix circular import
  deeplabcut/create_project/modelzoo.py
Labels: bug fix!, DLC3.0🔥

#2921 Add engine example to docstring in create_training_dataset()
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
Labels: Feature-request, DLC3.0🔥

#2908 _create_video_from_tracks fix
  deeplabcut/pose_estimation_pytorch/apis/tracklets.py
  deeplabcut/utils/make_labeled_video.py
Labels: bug fix!, DLC3.0🔥, 3.0.0rc8

#2843 Reading apply_prob for augmentation pipeline from config
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
Labels: enhancement, bug fix!, Tensorflow 2

#2918 Add a COLAB for human pose estimation using RTMPose
  examples/COLAB/COLAB_HumanPose_with_RTMPose.ipynb
Labels: COLAB, DLC3.0🔥

#2907 NMS for DEKR models
  deeplabcut/pose_estimation_pytorch/config/dekr/dekr_w18.yaml
  deeplabcut/pose_estimation_pytorch/config/dekr/dekr_w32.yaml
  deeplabcut/pose_estimation_pytorch/config/dekr/dekr_w48.yaml
  deeplabcut/pose_estimation_pytorch/models/predictors/dekr_predictor.py
Labels: DLC3.0🔥, 3.0.0rc8

#2926 Reading apply_prob for augmentation pipeline from config - LTS DLC 2
  deeplabcut/pose_estimation_tensorflow/datasets/pose_imgaug.py
Labels: bug fix!, Tensorflow 2

#2924 Default net type in config set according to engine
  deeplabcut/create_project/new.py
  deeplabcut/gui/tabs/create_training_dataset.py
  examples/testscript_multianimal.py
Labels: bug fix!, DLC3.0🔥

#2925 Save predicted poses in evaluate_multianimal_full() - LTS DLC 2
  deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py
Labels: Feature-request, Tensorflow 2

#2933 Add `bbox_margin` as a parameter to the pytorch config
  deeplabcut/pose_estimation_pytorch/config/base/aug_default.yaml
  deeplabcut/pose_estimation_pytorch/config/base/aug_top_down.yaml
  deeplabcut/pose_estimation_pytorch/data/base.py
  deeplabcut/pose_estimation_pytorch/data/dlcloader.py
  docs/pytorch/assets/bboxes_from_kpts.png
  docs/pytorch/pytorch_config.md
Labels: enhancement, DLC3.0🔥

#2936 Implement `snapshots_to_evaluate` for PyTorch models
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/apis/evaluation.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
Labels: bug fix!, DLC3.0🔥

#2935 Fix: check assembly length before getting first element.
  deeplabcut/pose_estimation_pytorch/apis/tracklets.py
Labels: bug fix!, DLC3.0🔥
