Repository DeepLabCut/DeepLabCut, pull requests merged in 2025-04, with the labels that each got.

#2939 Fix docstring
  deeplabcut/compat.py
Labels: documentation, DLC3.0🔥

#2919 Dynamic cropping for top-down models
  deeplabcut/pose_estimation_pytorch/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/apis/videos.py
  deeplabcut/pose_estimation_pytorch/models/predictors/sim_cc.py
  deeplabcut/pose_estimation_pytorch/runners/__init__.py
  deeplabcut/pose_estimation_pytorch/runners/dynamic_cropping.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
  tests/pose_estimation_pytorch/runners/test_dynamic_cropper.py
  tests/pose_estimation_pytorch/runners/test_runners_inference.py
Labels: DLC3.0🔥

#2956 Unsupervised ID tracking through the GUI - `set` of videos instead of `list`
  deeplabcut/gui/tabs/unsupervised_id_tracking.py
  deeplabcut/pose_tracking_pytorch/create_dataset.py
Labels: reID, DLC3.0🔥

#2957 `create_training_model_comparison`: check that `existing_shuffles` is not empty
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
Labels: DLC3.0🔥

#2958 Update bug_report.yml --> new assignment!
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: announcement

#2960 lower default LR to 5e-4 for ResNets and CSPNeXt
  deeplabcut/pose_estimation_pytorch/config/backbones/cspnext_m.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/cspnext_s.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/cspnext_x.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/resnet_101.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/resnet_50.yaml
Labels: DLC3.0🔥
