Repository DeepLabCut/DeepLabCut, pull requests merged in 2025-02, with the labels that each got.

#2860 Improvements to default configs
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/config/backbones/cspnext_m.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/cspnext_s.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/cspnext_x.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/resnet_101.yaml
  deeplabcut/pose_estimation_pytorch/config/backbones/resnet_50.yaml
  deeplabcut/pose_estimation_pytorch/config/base/aug_default.yaml
  deeplabcut/pose_estimation_pytorch/runners/train.py
Labels: enhancement, DLC3.0🔥

#2859 Dynamic update of pytorch config with dot notation
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/apis/prune_paf_graph.py
  deeplabcut/pose_estimation_pytorch/apis/train.py
  deeplabcut/pose_estimation_pytorch/config/__init__.py
  deeplabcut/pose_estimation_pytorch/config/utils.py
  deeplabcut/pose_estimation_pytorch/data/base.py
  deeplabcut/pose_estimation_pytorch/modelzoo/train_from_coco.py
  examples/testscript_pytorch_multi_animal.py
  examples/testscript_pytorch_single_animal.py
  examples/utils.py
  tests/pose_estimation_pytorch/config/test_make_pose_config.py
Labels: DLC3.0🔥

#2862 Pin TensorFlow according to OS; Fix DeepLabCut install in Colab to deal with new requirements.
  examples/COLAB/COLAB_3miceDemo.ipynb
  examples/COLAB/COLAB_DEMO_SuperAnimal.ipynb
  examples/COLAB/COLAB_DEMO_mouse_openfield.ipynb
  examples/COLAB/COLAB_DLC_ModelZoo.ipynb
  examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb
  examples/COLAB/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb
  examples/COLAB/COLAB_transformer_reID.ipynb
  setup.py
Labels: Installation, COLAB, Tensorflow 2

#2865 fix broken `train_network` argument `display_iters` in the GUI
  deeplabcut/gui/tabs/train_network.py
Labels: DLC3.0🔥

#2861 ReID Tracking dataset creation for PyTorch models
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py
  deeplabcut/pose_estimation_pytorch/apis/tracking_dataset.py
  deeplabcut/pose_estimation_pytorch/data/postprocessor.py
  deeplabcut/pose_estimation_pytorch/data/preprocessor.py
  deeplabcut/pose_estimation_pytorch/models/model.py
  deeplabcut/pose_estimation_pytorch/runners/inference.py
  deeplabcut/pose_estimation_pytorch/runners/shelving.py
  deeplabcut/pose_tracking_pytorch/apis.py
  deeplabcut/pose_tracking_pytorch/create_dataset.py
  deeplabcut/pose_tracking_pytorch/tracking_utils/preprocessing.py
  docs/pytorch/user_guide.md
  tests/pose_estimation_pytorch/apis/test_create_tracking_dataset.py
  tests/pose_estimation_pytorch/data/test_postprocessor.py
Labels: reID, DLC3.0🔥

#2869 Updates to the documentation - Maxim
  _config.yml
  _toc.yml
  deeplabcut/create_project/modelzoo.py
  deeplabcut/generate_training_dataset/metadata.py
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/utils/visualization.py
  docs/Governance.md
  docs/MISSION_AND_VALUES.md
  docs/ModelZoo.md
  docs/Overviewof3D.md
  docs/api/deeplabcut.analyze_videos.rst
  docs/api/deeplabcut.evaluate_network.rst
  docs/api/deeplabcut.label_frames.rst
  docs/api/deeplabcut.refine_labels.rst
  docs/api/deeplabcut.train_network.rst
  docs/beginner-guides/Training-Evaluation.md
  docs/beginner-guides/beginners-guide.md
  docs/beginner-guides/labeling.md
  docs/beginner-guides/manage-project.md
  docs/beginner-guides/video-analysis.md
  docs/convert_maDLC.md
  docs/course.md
  docs/deeplabcutlive.md
  docs/gui/PROJECT_GUI.md
  docs/gui/napari_GUI.md
  docs/pytorch/pytorch_config.md
  docs/quick-start/single_animal_quick_guide.md
  docs/recipes/BatchProcessing.md
  docs/recipes/ClusteringNapari.md
  docs/recipes/DLCMethods.md
  docs/recipes/MegaDetectorDLCLive.md
  docs/recipes/OpenVINO.md
  docs/recipes/UsingModelZooPupil.md
  docs/recipes/nn.md
  docs/recipes/pose_cfg_file_breakdown.md
  docs/recipes/publishing_notebooks_into_the_DLC_main_cookbook.md
  docs/roadmap.md
  docs/standardDeepLabCut_UserGuide.md
Labels: documentation, DLC3.0🔥

#2878 Fix video addition in VideoSelectionWidget
  deeplabcut/gui/components.py
  deeplabcut/gui/window.py
Labels: GUI, bug fix!

#2820 Fix check version timeout Version 2 (compatible with Windows and MacOS)
  deeplabcut/gui/window.py
  deeplabcut/utils/multiprocessing.py
  tests/utils/test_multiprocessing.py
Labels: 3.0.0rc7

#2863 fix entrypoint for dlc
  setup.py
Labels: Installation, bug fix!, DLC3.0🔥

#2883 Fix entrypoint - Requested changes
  deeplabcut/__main__.py
  setup.py
Labels: Installation, DLC3.0🔥

#2879 Fix assert in compute_detection_rmse()
  deeplabcut/core/metrics/distance_metrics.py
  tests/core/metrics/test_metrics_rmse_computation.py
Labels: bug fix!, DLC3.0🔥

#2885 Rename CLI command to dlc
  setup.py
Labels: DLC3.0🔥

#2884 improved handling of animal names when analyzing videos
  deeplabcut/pose_estimation_tensorflow/predict_videos.py
  deeplabcut/refine_training_dataset/stitch.py
  deeplabcut/utils/make_labeled_video.py
Labels: enhancement

#2890 add animal_names parameter for pytorch models
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
Labels: DLC3.0🔥

#2892 Improvements to the create project GUI
  deeplabcut/gui/tabs/create_project.py
  deeplabcut/gui/tabs/docs.py
Labels: enhancement, GUI, DLC3.0🔥

#2889 Set pcutoff per-bodypart with the when evaluating PyTorch models
  deeplabcut/compat.py
  deeplabcut/core/metrics/distance_metrics.py
  deeplabcut/pose_estimation_pytorch/apis/evaluate.py
  tests/pose_estimation_pytorch/apis/test_apis_evaluate.py
Labels: enhancement, DLC3.0🔥

#2901 Fixes failing tests
  deeplabcut/core/inferenceutils.py
  deeplabcut/core/metrics/distance_metrics.py
  deeplabcut/pose_estimation_pytorch/README.md
  deeplabcut/pose_estimation_pytorch/apis/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/evaluation.py
  deeplabcut/pose_estimation_pytorch/apis/tracking_dataset.py
  deeplabcut/pose_estimation_pytorch/apis/tracklets.py
  deeplabcut/pose_estimation_pytorch/apis/training.py
  deeplabcut/pose_estimation_pytorch/apis/videos.py
  deeplabcut/pose_estimation_pytorch/modelzoo/inference.py
  deeplabcut/pose_estimation_pytorch/modelzoo/train_from_coco.py
  examples/SUPERANIMAL/eval_zeroshot.py
  tests/pose_estimation_pytorch/apis/test_apis_evaluate.py
  tests/pose_estimation_pytorch/other/test_gaussian_targets.py
Labels: DLC3.0🔥

#2897 Implement create_pretrained_project() for Pytorch engine
  .gitignore
  deeplabcut/core/config.py
  deeplabcut/create_project/modelzoo.py
  deeplabcut/create_project/new.py
  deeplabcut/generate_training_dataset/metadata.py
  deeplabcut/modelzoo/utils.py
  deeplabcut/modelzoo/video_inference.py
  deeplabcut/modelzoo/weight_initialization.py
  deeplabcut/pose_estimation_pytorch/README.md
  deeplabcut/pose_estimation_pytorch/apis/analyze_images.py
  deeplabcut/pose_estimation_pytorch/apis/tracking_dataset.py
  deeplabcut/pose_estimation_pytorch/apis/training.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
  deeplabcut/pose_estimation_pytorch/apis/videos.py
  deeplabcut/pose_estimation_pytorch/apis/visualization.py
  deeplabcut/pose_estimation_pytorch/config/__init__.py
  deeplabcut/pose_estimation_pytorch/config/make_pose_config.py
  deeplabcut/pose_estimation_pytorch/config/utils.py
  deeplabcut/pose_estimation_pytorch/data/base.py
  deeplabcut/pose_estimation_pytorch/modelzoo/config.py
  deeplabcut/pose_estimation_pytorch/modelzoo/utils.py
  docs/recipes/UsingModelZooPupil.md
  examples/testscript_pretrained_models.py
  examples/testscript_superanimal_adaptation.py
  examples/testscript_superanimal_create_pretrained_project.py
  examples/testscript_superanimal_inference.py
  examples/testscript_superanimal_transfer_learning.py
  tests/pose_estimation_pytorch/config/test_make_pose_config.py
Labels: enhancement, ModelZoo, DLC3.0🔥

#2903 Improve tracklet creation for ID-only tracking
  deeplabcut/core/metrics/identity.py
  deeplabcut/pose_estimation_pytorch/apis/tracklets.py
  tests/pose_estimation_pytorch/apis/test_apis_evaluate.py
Labels: DLC3.0🔥

#2904 Error handling when extracting frames fails in the GUI
  deeplabcut/generate_training_dataset/frame_extraction.py
  deeplabcut/gui/tabs/extract_frames.py
  deeplabcut/gui/utils.py
Labels: GUI

#2881 [WIP] DLC 3.0 - Review documentation
  .github/workflows/publish-book.yml
  README.md
  _config.yml
  _toc.yml
  conda-environments/DEEPLABCUT.yaml
  conda-environments/DEEPLABCUT_M1.yaml
  deeplabcut/refine_training_dataset/outlier_frames.py
  deeplabcut/utils/visualization.py
  docs/Governance.md
  docs/MISSION_AND_VALUES.md
  docs/ModelZoo.md
  docs/Overviewof3D.md
  docs/UseOverviewGuide.md
  docs/api/deeplabcut.analyze_videos.rst
  docs/api/deeplabcut.convert_detections2tracklets.rst
  docs/api/deeplabcut.create_training_dataset_from_existing_split.rst
  docs/api/deeplabcut.evaluate_network.rst
  docs/api/deeplabcut.label_frames.rst
  docs/api/deeplabcut.refine_labels.rst
  docs/api/deeplabcut.stitch_tracklets.rst
  docs/api/deeplabcut.train_network.rst
  docs/beginner-guides/Training-Evaluation.md
  docs/beginner-guides/beginners-guide.md
  docs/beginner-guides/labeling.md
  docs/beginner-guides/manage-project.md
  docs/beginner-guides/video-analysis.md
  docs/benchmark.md
  docs/convert_maDLC.md
  docs/course.md
  docs/deeplabcutlive.md
  docs/gui/PROJECT_GUI.md
  docs/gui/napari_GUI.md
  docs/images/box1-multi.png
  docs/images/box1-single.png
  docs/installation.md
  docs/maDLC_UserGuide.md
  docs/pytorch/architectures.md
  docs/pytorch/pytorch_config.md
  docs/pytorch/user_guide.md
  docs/quick-start/single_animal_quick_guide.md
  docs/quick-start/tutorial_maDLC.md
  docs/recipes/BatchProcessing.md
  docs/recipes/ClusteringNapari.md
  docs/recipes/DLCMethods.md
  docs/recipes/MegaDetectorDLCLive.md
  docs/recipes/OpenVINO.md
  docs/recipes/OtherData.md
  docs/recipes/TechHardware.md
  docs/recipes/UsingModelZooPupil.md
  docs/recipes/installTips.md
  docs/recipes/nn.md
  docs/recipes/pose_cfg_file_breakdown.md
  docs/recipes/publishing_notebooks_into_the_DLC_main_cookbook.md
  docs/roadmap.md
  docs/standardDeepLabCut_UserGuide.md
Labels: WORK IN PROGRESS!, documentation, DLC3.0🔥

#2868 DeepLabCut 3.0 - Updates to COLABs and Notebooks for the PyTorch Engine
  deeplabcut/create_project/demo_data.py
  deeplabcut/pose_estimation_pytorch/config/base/base.yaml
  examples/COLAB/COLAB_3miceDemo.ipynb
  examples/COLAB/COLAB_DEMO_SuperAnimal.ipynb
  examples/COLAB/COLAB_DEMO_mouse_openfield.ipynb
  examples/COLAB/COLAB_YOURDATA_SuperAnimal.ipynb
  examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb
  examples/COLAB/COLAB_YOURDATA_maDLC_TrainNetwork_VideoAnalysis.ipynb
  examples/COLAB/COLAB_transformer_reID.ipynb
  examples/JUPYTER/Demo_3D_DeepLabCut.ipynb
  examples/JUPYTER/Demo_labeledexample_MouseReaching.ipynb
  examples/JUPYTER/Demo_labeledexample_Openfield.ipynb
  examples/JUPYTER/Demo_napari.ipynb
  examples/JUPYTER/Demo_yourowndata.ipynb
  examples/JUPYTER/Docker_TrainNetwork_VideoAnalysis.ipynb
Labels: howtousedlc, COLAB, Jupyter, DLC3.0🔥

#2911 Option to export top-down models without detectors
  deeplabcut/compat.py
  deeplabcut/pose_estimation_pytorch/apis/export.py
  deeplabcut/pose_estimation_pytorch/apis/utils.py
Labels: DLC3.0🔥

#2912 fix publish-book
  .github/workflows/publish-book.yml
Labels: documentation, DLC3.0🔥
