Repository DeepLabCut/DeepLabCut, pull requests merged in 2025-01, with the labels that each got.

#2826 `create_labeled_video` fails with single animal TensorFlow models
  deeplabcut/utils/make_labeled_video.py
  examples/testscript.py
Labels: bug fix!, DLC3.0🔥

#2827 Pins `numpy<2`, fix svd for `scipy>=1.11.0`
  deeplabcut/refine_training_dataset/stitch.py
  requirements.txt
  setup.py
Labels: dependencies

#2833 Improve `deeplabcut.pose_estimation_pytorch` imports
  deeplabcut/pose_estimation_pytorch/README.md
  deeplabcut/pose_estimation_pytorch/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/__init__.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_images.py
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/apis/evaluate.py
  deeplabcut/pose_estimation_pytorch/apis/train.py
  deeplabcut/pose_estimation_pytorch/apis/visualization.py
  deeplabcut/pose_estimation_pytorch/config/__init__.py
  deeplabcut/pose_estimation_pytorch/config/make_pose_config.py
  deeplabcut/pose_estimation_pytorch/data/__init__.py
  deeplabcut/pose_estimation_pytorch/data/base.py
  deeplabcut/pose_estimation_pytorch/modelzoo/inference.py
  tests/pose_estimation_pytorch/config/test_make_pose_config.py
Labels: DLC3.0🔥, 3.0.0rc7

#2844 Fix reading filtered state
  deeplabcut/gui/tabs/analyze_videos.py
  deeplabcut/gui/tabs/create_videos.py
  deeplabcut/gui/tabs/evaluate_network.py
Labels: GUI

#2846 Remove pickle5 dependency from madlc Colab
  examples/COLAB/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb
Labels: Installation, COLAB

#2849 Fix - setting cropping parameters in `analyze_videos` for PyTorch models
  deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py
  deeplabcut/pose_estimation_pytorch/models/predictors/single_predictor.py
Labels: DLC3.0🔥, 3.0.0rc7

#2850 Fixed `dropimagesduetolackofannotation` to work with single-animal data
  deeplabcut/generate_training_dataset/trainingsetmanipulation.py
Labels: backwards compatibility

#2858 fixes to label_frames, addition of docstring
  deeplabcut/gui/tabs/label_frames.py
Labels: enhancement, GUI
